name: Antti Brunni
favicon: null
layout_spectrum: 0.94374
typography_spectrum: 0.47966
title: 'Fouram. #4AM'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050706'
    - '#fdfdfd'
    - '#837351'
    - '#78a9d4'
    - '#c2cacd'
  brandStrength: 0.3525098788086325
  lightness: 0.9372240400407463
  saturation: 0.9947685860097408
  rhythmicContrast: 0.8930616991128772
purpose: []
