name: Fouram
favicon: null
layout_spectrum: 0.63469
typography_spectrum: 0.26169
title: 'Fouram. #4AM'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#24131d'
    - '#fefefe'
    - '#39634d'
    - '#97a1a3'
    - '#44a4a3'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
