name: Antti Brunni
favicon: null
layout_spectrum: 0.008809673367068172
typography_spectrum: 0.7565964856185019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3525098788086325
  lightness: 0.9372240400407463
  saturation: 0.9947685860097408
  rhythmicContrast: 0.8930616991128772
purpose: []
