typography_spectrum: 0.26169
color:
  brandColors:
    - '#24131d'
    - '#fefefe'
    - '#39634d'
    - '#97a1a3'
    - '#44a4a3'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.63469
analytics:
  google: null
  facebook: null
  twitter: null
name: FOURAM
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Wake up early in the digital to see the sunrise
purpose: []
